# ~/Bastion/BASTION3/keepalived/keepalived.conf
vrrp_script chk_haproxy {
    script "/usr/bin/pgrep haproxy || exit 1"
    interval 2
    weight 2
}

vrrp_instance VI_BASTION {
    state BACKUP
    interface ens33
    virtual_router_id 51
    priority 50
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ${VRRP_AUTH_PASS}
    }
    virtual_ipaddress {
        192.168.200.110/24
    }
    track_script {
        chk_haproxy
    }
}
